# Generated by Django 3.2.5 on 2021-07-30 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoes',
            old_name='quality',
            new_name='rating',
        ),
    ]
